title: Testing Pito
author: Pito Lucania
version: 0.0.0
documentclass: article
header: header.pto
entry: main.pto
include:
  - fn.main_fn.py
package:
  - fontspec
  - polyglossia
  - amsmath
  - geometry[a4paper, left=1.5in, right=1in, top=1in, bottom=1in]
  - fancyhdr
setmainlanguage: thai
setotherlanguage: english
newfontfamily.thaifont: Sarabun
pagenumbering: arabic